version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 0SdPLo1BvsRIgbGEh4tOVCT358U9762x
      POSTGRES_DB: zeabur
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: zeabur
      DB_POSTGRESDB_USER: root
      DB_POSTGRESDB_PASSWORD: 0SdPLo1BvsRIgbGEh4tOVCT358U9762x
      N8N_PORT: 5678
      N8N_HOST: n8n.local
      WEBHOOK_URL: http://localhost:5678
      GENERIC_TIMEZONE: Asia/Taipei
      N8N_ENABLE_MCP: "true"
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
  n8n_postgres_data:
