name: github-mcp-server

services:
  mcp:
    build:
      base: node:18
      install: npm install
    run:
      command: npm run start
    env:
      PORT: 3000
      NODE_ENV: production
      MCP_SERVER_SECRET: my-secret
      ALLOWED_ORIGINS: "*"
      DATABASE_URL: ${postgresql.DATABASE_URL}
    ports:
      - 3000

  postgresql:
    template: postgresql
    env:
      POSTGRES_DB: mcpdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: supersecurepw
